[profile.default]
formatter = "forge-fmt"
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]